### ISSUE TITLE
有关网络设计的一些问题

### ISSUE THREAD

**Issue by charles-lich** [chunyuanY/Dialogue#1]
我们分析了优化目标及网络结构，发现存在一些问题，在此备注：
1、论文里提到的丢弃match_score < r的utterance，这个操作会导致被丢弃的utterance相关的打分部分的梯度一直是0，这些utterance训练过程中很难被"曝光"出来，最终会影响匹配效果。同时已经被"曝光"的utterance没有任何方法能够被移除。

2、这个网络和初始化强相关，如果初始化时所有score均大于0.5（实验中基本如此），不会有utterance被丢弃（网络优化了词向量，但词到match_score有几个全连接过渡层，这几个过渡层网络没有丢弃某些turn的优化能力），反之如果都低于0.5，网络就会一直在随机猜测状态中。

3、网络没有考虑mask的影响，这对于最终的rnn的效果是有影响的.

4、我们在pytorch源码上移除了utterance_selector和word_selector，ubuntu上R10@1达到79.8%，观察match_score，发现没有context被丢弃。

以上，感谢解答。

**Comment by chunyuanY** [comment]
同学，你好。感谢你的提出的意见。对一些疑问解答如下：
关于问题1，2，4，实验中我们发现如果把utterance过滤掉确实会导致performance表现不好，所以我们是用score对context加权，对重要的context给更高的权重。
关于问题3，我之前有尝试过对pad的词加mask，但是效果不好，所以就去掉了。如果你那边有好的经验欢迎分享。

如果还有什么后续问题，可以邮箱联系我，我的邮箱在论文中可以找到，欢迎交流和合作。

**Comment by chunyuanY** [comment]
> 我们分析了优化目标及网络结构，发现存在一些问题，在此备注：
> 1、论文里提到的丢弃match_score < r的utterance，这个操作会导致被丢弃的utterance相关的打分部分的梯度一直是0，这些utterance训练过程中很难被"曝光"出来，最终会影响匹配效果。同时已经被"曝光"的utterance没有任何方法能够被移除。
> 
> 2、这个网络和初始化强相关，如果初始化时所有score均大于0.5（实验中基本如此），不会有utterance被丢弃（网络优化了词向量，但词到match_score有几个全连接过渡层，这几个过渡层网络没有丢弃某些turn的优化能力），反之如果都低于0.5，网络就会一直在随机猜测状态中。
> 
> 3、网络没有考虑mask的影响，这对于最终的rnn的效果是有影响的.
> 
> 4、我们在pytorch源码上移除了utterance_selector和word_selector，ubuntu上R10@1达到79.8%，观察match_score，发现没有context被丢弃。
> 
> 以上，感谢解答。

同学，你好。感谢你的提出的意见。对一些疑问解答如下：
关于问题1，2，4，实验中我们发现如果把utterance过滤掉确实会导致performance表现不好，所以我们是用score对context加权，对重要的context给更高的权重。
关于问题3，我之前有尝试过对pad的词加mask，但是效果不好，所以就去掉了。如果你那边有好的经验欢迎分享。

如果还有什么后续问题，可以邮箱联系我，我的邮箱在论文中可以找到，欢迎交流和合作。
